// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	time "time"

	internal "github.com/astepanovs/ztime/internal"
	mock "github.com/stretchr/testify/mock"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: tag, startedAt, note
func (_m *MockStore) Create(tag string, startedAt time.Time, note string) (*internal.Entry, error) {
	ret := _m.Called(tag, startedAt, note)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *internal.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time, string) (*internal.Entry, error)); ok {
		return rf(tag, startedAt, note)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, string) *internal.Entry); ok {
		r0 = rf(tag, startedAt, note)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, string) error); ok {
		r1 = rf(tag, startedAt, note)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tag string
//   - startedAt time.Time
//   - note string
func (_e *MockStore_Expecter) Create(tag interface{}, startedAt interface{}, note interface{}) *MockStore_Create_Call {
	return &MockStore_Create_Call{Call: _e.mock.On("Create", tag, startedAt, note)}
}

func (_c *MockStore_Create_Call) Run(run func(tag string, startedAt time.Time, note string)) *MockStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Time), args[2].(string))
	})
	return _c
}

func (_c *MockStore_Create_Call) Return(_a0 *internal.Entry, _a1 error) *MockStore_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_Create_Call) RunAndReturn(run func(string, time.Time, string) (*internal.Entry, error)) *MockStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateActivity provides a mock function with given fields: entryID, occurredAt, text
func (_m *MockStore) CreateActivity(entryID int64, occurredAt time.Time, text string) (*internal.Activity, error) {
	ret := _m.Called(entryID, occurredAt, text)

	if len(ret) == 0 {
		panic("no return value specified for CreateActivity")
	}

	var r0 *internal.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, time.Time, string) (*internal.Activity, error)); ok {
		return rf(entryID, occurredAt, text)
	}
	if rf, ok := ret.Get(0).(func(int64, time.Time, string) *internal.Activity); ok {
		r0 = rf(entryID, occurredAt, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, time.Time, string) error); ok {
		r1 = rf(entryID, occurredAt, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_CreateActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateActivity'
type MockStore_CreateActivity_Call struct {
	*mock.Call
}

// CreateActivity is a helper method to define mock.On call
//   - entryID int64
//   - occurredAt time.Time
//   - text string
func (_e *MockStore_Expecter) CreateActivity(entryID interface{}, occurredAt interface{}, text interface{}) *MockStore_CreateActivity_Call {
	return &MockStore_CreateActivity_Call{Call: _e.mock.On("CreateActivity", entryID, occurredAt, text)}
}

func (_c *MockStore_CreateActivity_Call) Run(run func(entryID int64, occurredAt time.Time, text string)) *MockStore_CreateActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(time.Time), args[2].(string))
	})
	return _c
}

func (_c *MockStore_CreateActivity_Call) Return(_a0 *internal.Activity, _a1 error) *MockStore_CreateActivity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_CreateActivity_Call) RunAndReturn(run func(int64, time.Time, string) (*internal.Activity, error)) *MockStore_CreateActivity_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithActivity provides a mock function with given fields: tag, startedAt, text
func (_m *MockStore) CreateWithActivity(tag string, startedAt time.Time, text string) (*internal.Entry, *internal.Activity, error) {
	ret := _m.Called(tag, startedAt, text)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithActivity")
	}

	var r0 *internal.Entry
	var r1 *internal.Activity
	var r2 error
	if rf, ok := ret.Get(0).(func(string, time.Time, string) (*internal.Entry, *internal.Activity, error)); ok {
		return rf(tag, startedAt, text)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, string) *internal.Entry); ok {
		r0 = rf(tag, startedAt, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, string) *internal.Activity); ok {
		r1 = rf(tag, startedAt, text)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*internal.Activity)
		}
	}

	if rf, ok := ret.Get(2).(func(string, time.Time, string) error); ok {
		r2 = rf(tag, startedAt, text)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStore_CreateWithActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithActivity'
type MockStore_CreateWithActivity_Call struct {
	*mock.Call
}

// CreateWithActivity is a helper method to define mock.On call
//   - tag string
//   - startedAt time.Time
//   - text string
func (_e *MockStore_Expecter) CreateWithActivity(tag interface{}, startedAt interface{}, text interface{}) *MockStore_CreateWithActivity_Call {
	return &MockStore_CreateWithActivity_Call{Call: _e.mock.On("CreateWithActivity", tag, startedAt, text)}
}

func (_c *MockStore_CreateWithActivity_Call) Run(run func(tag string, startedAt time.Time, text string)) *MockStore_CreateWithActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Time), args[2].(string))
	})
	return _c
}

func (_c *MockStore_CreateWithActivity_Call) Return(_a0 *internal.Entry, _a1 *internal.Activity, _a2 error) *MockStore_CreateWithActivity_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStore_CreateWithActivity_Call) RunAndReturn(run func(string, time.Time, string) (*internal.Entry, *internal.Activity, error)) *MockStore_CreateWithActivity_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockStore) Delete(id int64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int64
func (_e *MockStore_Expecter) Delete(id interface{}) *MockStore_Delete_Call {
	return &MockStore_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockStore_Delete_Call) Run(run func(id int64)) *MockStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockStore_Delete_Call) Return(_a0 error) *MockStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Delete_Call) RunAndReturn(run func(int64) error) *MockStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Edit provides a mock function with given fields: id, p
func (_m *MockStore) Edit(id int64, p internal.EditParams) (*internal.Entry, error) {
	ret := _m.Called(id, p)

	if len(ret) == 0 {
		panic("no return value specified for Edit")
	}

	var r0 *internal.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, internal.EditParams) (*internal.Entry, error)); ok {
		return rf(id, p)
	}
	if rf, ok := ret.Get(0).(func(int64, internal.EditParams) *internal.Entry); ok {
		r0 = rf(id, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, internal.EditParams) error); ok {
		r1 = rf(id, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_Edit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Edit'
type MockStore_Edit_Call struct {
	*mock.Call
}

// Edit is a helper method to define mock.On call
//   - id int64
//   - p internal.EditParams
func (_e *MockStore_Expecter) Edit(id interface{}, p interface{}) *MockStore_Edit_Call {
	return &MockStore_Edit_Call{Call: _e.mock.On("Edit", id, p)}
}

func (_c *MockStore_Edit_Call) Run(run func(id int64, p internal.EditParams)) *MockStore_Edit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(internal.EditParams))
	})
	return _c
}

func (_c *MockStore_Edit_Call) Return(_a0 *internal.Entry, _a1 error) *MockStore_Edit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_Edit_Call) RunAndReturn(run func(int64, internal.EditParams) (*internal.Entry, error)) *MockStore_Edit_Call {
	_c.Call.Return(run)
	return _c
}

// EntryAt provides a mock function with given fields: tag, at
func (_m *MockStore) EntryAt(tag string, at time.Time) (*internal.Entry, error) {
	ret := _m.Called(tag, at)

	if len(ret) == 0 {
		panic("no return value specified for EntryAt")
	}

	var r0 *internal.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time) (*internal.Entry, error)); ok {
		return rf(tag, at)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time) *internal.Entry); ok {
		r0 = rf(tag, at)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time) error); ok {
		r1 = rf(tag, at)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_EntryAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EntryAt'
type MockStore_EntryAt_Call struct {
	*mock.Call
}

// EntryAt is a helper method to define mock.On call
//   - tag string
//   - at time.Time
func (_e *MockStore_Expecter) EntryAt(tag interface{}, at interface{}) *MockStore_EntryAt_Call {
	return &MockStore_EntryAt_Call{Call: _e.mock.On("EntryAt", tag, at)}
}

func (_c *MockStore_EntryAt_Call) Run(run func(tag string, at time.Time)) *MockStore_EntryAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Time))
	})
	return _c
}

func (_c *MockStore_EntryAt_Call) Return(_a0 *internal.Entry, _a1 error) *MockStore_EntryAt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_EntryAt_Call) RunAndReturn(run func(string, time.Time) (*internal.Entry, error)) *MockStore_EntryAt_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: id
func (_m *MockStore) Get(id int64) (*internal.Entry, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *internal.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*internal.Entry, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *internal.Entry); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id int64
func (_e *MockStore_Expecter) Get(id interface{}) *MockStore_Get_Call {
	return &MockStore_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockStore_Get_Call) Run(run func(id int64)) *MockStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockStore_Get_Call) Return(_a0 *internal.Entry, _a1 error) *MockStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_Get_Call) RunAndReturn(run func(int64) (*internal.Entry, error)) *MockStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// LastEntryBefore provides a mock function with given fields: tag, at
func (_m *MockStore) LastEntryBefore(tag string, at time.Time) (*internal.Entry, error) {
	ret := _m.Called(tag, at)

	if len(ret) == 0 {
		panic("no return value specified for LastEntryBefore")
	}

	var r0 *internal.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time) (*internal.Entry, error)); ok {
		return rf(tag, at)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time) *internal.Entry); ok {
		r0 = rf(tag, at)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time) error); ok {
		r1 = rf(tag, at)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_LastEntryBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastEntryBefore'
type MockStore_LastEntryBefore_Call struct {
	*mock.Call
}

// LastEntryBefore is a helper method to define mock.On call
//   - tag string
//   - at time.Time
func (_e *MockStore_Expecter) LastEntryBefore(tag interface{}, at interface{}) *MockStore_LastEntryBefore_Call {
	return &MockStore_LastEntryBefore_Call{Call: _e.mock.On("LastEntryBefore", tag, at)}
}

func (_c *MockStore_LastEntryBefore_Call) Run(run func(tag string, at time.Time)) *MockStore_LastEntryBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Time))
	})
	return _c
}

func (_c *MockStore_LastEntryBefore_Call) Return(_a0 *internal.Entry, _a1 error) *MockStore_LastEntryBefore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_LastEntryBefore_Call) RunAndReturn(run func(string, time.Time) (*internal.Entry, error)) *MockStore_LastEntryBefore_Call {
	_c.Call.Return(run)
	return _c
}

// LastStopped provides a mock function with given fields: tag
func (_m *MockStore) LastStopped(tag string) (*internal.Entry, error) {
	ret := _m.Called(tag)

	if len(ret) == 0 {
		panic("no return value specified for LastStopped")
	}

	var r0 *internal.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*internal.Entry, error)); ok {
		return rf(tag)
	}
	if rf, ok := ret.Get(0).(func(string) *internal.Entry); ok {
		r0 = rf(tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_LastStopped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastStopped'
type MockStore_LastStopped_Call struct {
	*mock.Call
}

// LastStopped is a helper method to define mock.On call
//   - tag string
func (_e *MockStore_Expecter) LastStopped(tag interface{}) *MockStore_LastStopped_Call {
	return &MockStore_LastStopped_Call{Call: _e.mock.On("LastStopped", tag)}
}

func (_c *MockStore_LastStopped_Call) Run(run func(tag string)) *MockStore_LastStopped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStore_LastStopped_Call) Return(_a0 *internal.Entry, _a1 error) *MockStore_LastStopped_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_LastStopped_Call) RunAndReturn(run func(string) (*internal.Entry, error)) *MockStore_LastStopped_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: f
func (_m *MockStore) List(f internal.LogFilter) ([]internal.Entry, error) {
	ret := _m.Called(f)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []internal.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(internal.LogFilter) ([]internal.Entry, error)); ok {
		return rf(f)
	}
	if rf, ok := ret.Get(0).(func(internal.LogFilter) []internal.Entry); ok {
		r0 = rf(f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]internal.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(internal.LogFilter) error); ok {
		r1 = rf(f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - f internal.LogFilter
func (_e *MockStore_Expecter) List(f interface{}) *MockStore_List_Call {
	return &MockStore_List_Call{Call: _e.mock.On("List", f)}
}

func (_c *MockStore_List_Call) Run(run func(f internal.LogFilter)) *MockStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(internal.LogFilter))
	})
	return _c
}

func (_c *MockStore_List_Call) Return(_a0 []internal.Entry, _a1 error) *MockStore_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_List_Call) RunAndReturn(run func(internal.LogFilter) ([]internal.Entry, error)) *MockStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListActivities provides a mock function with given fields: filter
func (_m *MockStore) ListActivities(filter internal.ActivityFilter) ([]internal.Activity, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for ListActivities")
	}

	var r0 []internal.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(internal.ActivityFilter) ([]internal.Activity, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(internal.ActivityFilter) []internal.Activity); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]internal.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(internal.ActivityFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListActivities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActivities'
type MockStore_ListActivities_Call struct {
	*mock.Call
}

// ListActivities is a helper method to define mock.On call
//   - filter internal.ActivityFilter
func (_e *MockStore_Expecter) ListActivities(filter interface{}) *MockStore_ListActivities_Call {
	return &MockStore_ListActivities_Call{Call: _e.mock.On("ListActivities", filter)}
}

func (_c *MockStore_ListActivities_Call) Run(run func(filter internal.ActivityFilter)) *MockStore_ListActivities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(internal.ActivityFilter))
	})
	return _c
}

func (_c *MockStore_ListActivities_Call) Return(_a0 []internal.Activity, _a1 error) *MockStore_ListActivities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListActivities_Call) RunAndReturn(run func(internal.ActivityFilter) ([]internal.Activity, error)) *MockStore_ListActivities_Call {
	_c.Call.Return(run)
	return _c
}

// OpenEntry provides a mock function with given fields: tag
func (_m *MockStore) OpenEntry(tag string) (*internal.Entry, error) {
	ret := _m.Called(tag)

	if len(ret) == 0 {
		panic("no return value specified for OpenEntry")
	}

	var r0 *internal.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*internal.Entry, error)); ok {
		return rf(tag)
	}
	if rf, ok := ret.Get(0).(func(string) *internal.Entry); ok {
		r0 = rf(tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_OpenEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenEntry'
type MockStore_OpenEntry_Call struct {
	*mock.Call
}

// OpenEntry is a helper method to define mock.On call
//   - tag string
func (_e *MockStore_Expecter) OpenEntry(tag interface{}) *MockStore_OpenEntry_Call {
	return &MockStore_OpenEntry_Call{Call: _e.mock.On("OpenEntry", tag)}
}

func (_c *MockStore_OpenEntry_Call) Run(run func(tag string)) *MockStore_OpenEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStore_OpenEntry_Call) Return(_a0 *internal.Entry, _a1 error) *MockStore_OpenEntry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_OpenEntry_Call) RunAndReturn(run func(string) (*internal.Entry, error)) *MockStore_OpenEntry_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields: tag, stoppedAt, reason, breakQualifies
func (_m *MockStore) Stop(tag string, stoppedAt time.Time, reason string, breakQualifies bool) (*internal.Entry, error) {
	ret := _m.Called(tag, stoppedAt, reason, breakQualifies)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 *internal.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time, string, bool) (*internal.Entry, error)); ok {
		return rf(tag, stoppedAt, reason, breakQualifies)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, string, bool) *internal.Entry); ok {
		r0 = rf(tag, stoppedAt, reason, breakQualifies)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, string, bool) error); ok {
		r1 = rf(tag, stoppedAt, reason, breakQualifies)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockStore_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - tag string
//   - stoppedAt time.Time
//   - reason string
//   - breakQualifies bool
func (_e *MockStore_Expecter) Stop(tag interface{}, stoppedAt interface{}, reason interface{}, breakQualifies interface{}) *MockStore_Stop_Call {
	return &MockStore_Stop_Call{Call: _e.mock.On("Stop", tag, stoppedAt, reason, breakQualifies)}
}

func (_c *MockStore_Stop_Call) Run(run func(tag string, stoppedAt time.Time, reason string, breakQualifies bool)) *MockStore_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Time), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockStore_Stop_Call) Return(_a0 *internal.Entry, _a1 error) *MockStore_Stop_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_Stop_Call) RunAndReturn(run func(string, time.Time, string, bool) (*internal.Entry, error)) *MockStore_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// UndoLast provides a mock function with given fields: tag
func (_m *MockStore) UndoLast(tag string) (*internal.UndoResult, error) {
	ret := _m.Called(tag)

	if len(ret) == 0 {
		panic("no return value specified for UndoLast")
	}

	var r0 *internal.UndoResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*internal.UndoResult, error)); ok {
		return rf(tag)
	}
	if rf, ok := ret.Get(0).(func(string) *internal.UndoResult); ok {
		r0 = rf(tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.UndoResult)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_UndoLast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UndoLast'
type MockStore_UndoLast_Call struct {
	*mock.Call
}

// UndoLast is a helper method to define mock.On call
//   - tag string
func (_e *MockStore_Expecter) UndoLast(tag interface{}) *MockStore_UndoLast_Call {
	return &MockStore_UndoLast_Call{Call: _e.mock.On("UndoLast", tag)}
}

func (_c *MockStore_UndoLast_Call) Run(run func(tag string)) *MockStore_UndoLast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStore_UndoLast_Call) Return(_a0 *internal.UndoResult, _a1 error) *MockStore_UndoLast_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_UndoLast_Call) RunAndReturn(run func(string) (*internal.UndoResult, error)) *MockStore_UndoLast_Call {
	_c.Call.Return(run)
	return _c
}

// UndoLastActivity provides a mock function with no fields
func (_m *MockStore) UndoLastActivity() (*internal.Activity, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UndoLastActivity")
	}

	var r0 *internal.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func() (*internal.Activity, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *internal.Activity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_UndoLastActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UndoLastActivity'
type MockStore_UndoLastActivity_Call struct {
	*mock.Call
}

// UndoLastActivity is a helper method to define mock.On call
func (_e *MockStore_Expecter) UndoLastActivity() *MockStore_UndoLastActivity_Call {
	return &MockStore_UndoLastActivity_Call{Call: _e.mock.On("UndoLastActivity")}
}

func (_c *MockStore_UndoLastActivity_Call) Run(run func()) *MockStore_UndoLastActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_UndoLastActivity_Call) Return(_a0 *internal.Activity, _a1 error) *MockStore_UndoLastActivity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_UndoLastActivity_Call) RunAndReturn(run func() (*internal.Activity, error)) *MockStore_UndoLastActivity_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
